package me.bechberger.testorder.changes;

import org.objectweb.asm.Opcodes;

/**
 * Centralised "should this member participate in change detection?" rule.
 * Mirrors the agent-side filter so the hash store, call graph, and runtime
 * tracker stay in sync.
 *
 * <p>
 * Synthetic/bridge methods (lambda bodies, javac bridges, switch-table
 * accessors, Kotlin {@code $default}/{@code $annotations}, Scala bridges) are
 * generated by the compiler and never instrumented at runtime — including them
 * here only produces noise in the change report.
 *
 * <p>
 * {@code <init>} and {@code <clinit>} carry no synthetic bit and continue to be
 * tracked.
 */
final class MemberFilter {

	private MemberFilter() {
	}

	/**
	 * @return false when the access flags indicate a compiler-synthesized member
	 *         that should be ignored for hashing and call-graph purposes.
	 */
	static boolean shouldTrack(int access) {
		return (access & (Opcodes.ACC_SYNTHETIC | Opcodes.ACC_BRIDGE)) == 0;
	}
}
