import pathlib

# Build the file content piece by piece to avoid escaping issues
lines = [
    "package me.bechberger.testorder.changes;",
    "",
    "import org.junit.jupiter.api.Test;",
    "import org.junit.jupiter.api.io.TempDir;",
    "",
    "import java.io.IOException;",
    "import java.nio.file.Files;",
    "import java.nio.file.Path;",
    "import java.util.Set;",
    "",
    "import static org.junit.jupiter.api.Assertions.*;",
    "",
    "class FileHashStoreTest {",
    "",
    "    @TempDir",
    "    Path tempDir;",
    "",
    "    @Test",
    "    void scanAndSaveRoundTrip() throws IOException {",
    '        Path srcRoot = tempDir.resolve("src");',
    '        Files.createDirectories(srcRoot.resolve("com/example"));',
    '        Files.writeString(srcRoot.resolve("com/example/Foo.java"), "public class Foo {}");',
    '        Files.writeString(srcRoot.resolve("com/example/Bar.java"), "public class Bar {}");',
    "",
    "        FileHashStore store = FileHashStore.scan(srcRoot);",
    "        assertEquals(2, store.getHashes().size());",
    "",
    '        Path hashFile = tempDir.resolve("hashes.gz");',
    "        store.save(hashFile);",
    "",
    "        FileHashStore loaded = FileHashStore.load(hashFile);",
    "        assertEquals(store, loaded);",
    "    }",
    "",
    "    @Test",
    "    void detectChangedFile() throws IOException {",
    '        Path srcRoot = tempDir.resolve("src");',
    '        Files.createDirectories(srcRoot.resolve("com/example"));',
    '        Files.writeString(srcRoot.resolve("com/example/Foo.java"), "public class Foo {}");',
    '        Files.writeString(srcRoot.resolve("com/example/Bar.java"), "public class Bar {}");',
    "",
    "        FileHashStore before = FileHashStore.scan(srcRoot);",
    '        Files.writeString(srcRoot.resolve("com/example/Foo.java"), "public class Foo { int x; }");',
    "        FileHashStore after = FileHashStore.scan(srcRoot);",
    "        Set<String> changed = after.getChangedFiles(before);",
    "",
    "        assertEquals(1, changed.size());",
    '        assertTrue(changed.contains("com/example/Foo.java"));',
    "    }",
    "",
    "    @Test",
    "    void detectNewFile() throws IOException {",
    '        Path srcRoot = tempDir.resolve("src");',
    '        Files.createDirectories(srcRoot.resolve("com/example"));',
    '        Files.writeString(srcRoot.resolve("com/example/Foo.java"), "public class Foo {}");',
    "",
    "        FileHashStore before = FileHashStore.scan(srcRoot);",
    '        Files.writeString(srcRoot.resolve("com/example/Baz.java"), "public class Baz {}");',
    "        FileHashStore after = FileHashStore.scan(srcRoot);",
    "        Set<String> changed = after.getChangedFiles(before);",
    "",
    "        assertEquals(1, changed.size());",
    '        assertTrue(changed.contains("com/example/Baz.java"));',
    "    }",
    "",
    "    @Test",
    "    void detectDeletedFile() throws IOException {",
    '        Path srcRoot = tempDir.resolve("src");',
    '        Files.createDirectories(srcRoot.resolve("com/example"));',
    '        Files.writeString(srcRoot.resolve("com/example/Foo.java"), "public class Foo {}");',
    '        Files.writeString(srcRoot.resolve("com/example/Bar.java"), "public class Bar {}");',
    "",
    "        FileHashStore before = FileHashStore.scan(srcRoot);",
    '        Files.delete(srcRoot.resolve("com/example/Bar.java"));',
    "        FileHashStore after = FileHashStore.scan(srcRoot);",
    "        Set<String> changed = after.getChangedFiles(before);",
    "",
    "        assertEquals(1, changed.size());",
    '        assertTrue(changed.contains("com/example/Bar.java"));',
    "    }",
    "",
    "    @Test",
    "    void filesToClassNames() {",
    '        Set<String> paths = Set.of("com/example/Foo.java", "com/example/util/Helper.java");',
    "        Set<String> classNames = SourceFileModel.filesToClassNames(paths);",
    '        assertEquals(Set.of("com.example.Foo", "com.example.util.Helper"), classNames);',
    "    }",
    "",
    "    @Test",
    "    void noChanges() throws IOException {",
    '        Path srcRoot = tempDir.resolve("src");',
    '        Files.createDirectories(srcRoot.resolve("com/example"));',
    '        Files.writeString(srcRoot.resolve("com/example/Foo.java"), "public class Foo {}");',
    "",
    "        FileHashStore store1 = FileHashStore.scan(srcRoot);",
    "        FileHashStore store2 = FileHashStore.scan(srcRoot);",
    "        Set<String> changed = store2.getChangedFiles(store1);",
    "        assertTrue(changed.isEmpty());",
    "    }",
    "",
    "    @Test",
    "    void emptySourceRoot() throws IOException {",
    '        Path srcRoot = tempDir.resolve("empty");',
    "        Files.createDirectories(srcRoot);",
    "        FileHashStore store = FileHashStore.scan(srcRoot);",
    "        assertTrue(store.getHashes().isEmpty());",
    "    }",
    "",
    "    @Test",
    "    void nonExistentSourceRoot() throws IOException {",
    '        Path srcRoot = tempDir.resolve("nonexistent");',
    "        FileHashStore store = FileHashStore.scan(srcRoot);",
    "        assertTrue(store.getHashes().isEmpty());",
    "    }",
    "",
    "    @Test",
    "    void scanProducesForwardSlashPaths() throws IOException {",
    '        Path srcRoot = tempDir.resolve("src");',
    '        Files.createDirectories(srcRoot.resolve("com/example/util"));',
    '        Files.writeString(srcRoot.resolve("com/example/util/Helper.java"), "public class Helper {}");',
    "",
    "        FileHashStore store = FileHashStore.scan(srcRoot);",
    "        for (String key : store.getHashes().keySet()) {",
    # Java: assertFalse(key.contains("\\"), ...)
    '            assertFalse(key.contains("' + "\\" + "\\" + '"),',
    '                    "Path key should use forward slashes, got: " + key);',
    "        }",
    '        assertTrue(store.getHashes().containsKey("com/example/util/Helper.java"),',
    '                "Key should be \'com/example/util/Helper.java\', actual keys: " + store.getHashes().keySet());',
    "    }",
    "",
    "    // \u2500\u2500 Tier 3d: cross-platform paths & corrupt-file load \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
    "",
    "    @Test",
    "    void roundTripPreservesForwardSlashKeysAfterLoad() throws IOException {",
    '        Path srcRoot = tempDir.resolve("src");',
    '        Files.createDirectories(srcRoot.resolve("com/example/util"));',
    '        Files.writeString(srcRoot.resolve("com/example/util/Service.java"), "class Service {}");',
    "",
    "        FileHashStore store = FileHashStore.scan(srcRoot);",
    '        Path hashFile = tempDir.resolve("hashes.lz4");',
    "        store.save(hashFile);",
    "",
    "        FileHashStore loaded = FileHashStore.load(hashFile);",
    "        for (String key : loaded.getHashes().keySet()) {",
    '            assertFalse(key.contains("' + "\\" + "\\" + '"),',
    '                    "Loaded keys must use forward slashes, got: " + key);',
    "        }",
    '        assertTrue(loaded.getHashes().containsKey("com/example/util/Service.java"),',
    '                "Key must be \'com/example/util/Service.java\' after round-trip; actual: "',
    "                        + loaded.getHashes().keySet());",
    "    }",
    "",
    "    @Test",
    "    void getChangedFilesProducesNoFalsePositivesWhenContentUnchanged() throws IOException {",
    '        Path srcRoot = tempDir.resolve("src");',
    '        Files.createDirectories(srcRoot.resolve("a/b/c"));',
    '        Files.writeString(srcRoot.resolve("a/b/c/Deep.java"), "class Deep {}");',
    "",
    "        FileHashStore before = FileHashStore.scan(srcRoot);",
    '        Path hashFile = tempDir.resolve("hashes.lz4");',
    "        before.save(hashFile);",
    "",
    "        FileHashStore after = FileHashStore.scan(srcRoot);",
    "        Set<String> changed = after.getChangedFiles(FileHashStore.load(hashFile));",
    "        assertTrue(changed.isEmpty(),",
    '                "No false positives expected when content is unchanged after round-trip; got: " + changed);',
    "    }",
    "",
    "    @Test",
    "    void loadTruncatedLz4FileThrowsIOException() throws IOException {",
    '        Path hashFile = tempDir.resolve("truncated.lz4");',
    "        byte[] truncated = {0x04, 0x22, 0x4D, 0x18, 0x60, 0x70, 0x73};",
    "        Files.write(hashFile, truncated);",
    "        assertThrows(IOException.class, () -> FileHashStore.load(hashFile),",
    '                "Loading a truncated LZ4 file must throw IOException");',
    "    }",
    "",
    "    @Test",
    "    void loadCompletelyRandomBytesThrowsIOException() throws IOException {",
    '        Path hashFile = tempDir.resolve("random.lz4");',
    "        byte[] random = new byte[64];",
    "        for (int i = 0; i < random.length; i++) random[i] = (byte)(i * 13 + 7);",
    "        Files.write(hashFile, random);",
    "        assertThrows(IOException.class, () -> FileHashStore.load(hashFile),",
    '                "Loading random bytes as LZ4 must throw IOException");',
    "    }",
    "}",
]

content = "\n".join(lines) + "\n"

p = pathlib.Path('/Users/i560383_1/code/experiments/test-order/test-order-core/src/test/java/me/bechberger/testorder/changes/FileHashStoreTest.java')
p.write_text(content)
print(f'Written {len(content.splitlines())} lines')

# Quick sanity check
assert 'class FileHashStoreTest {' in content
assert content.count('class FileHashStoreTest') == 1
assert content.endswith('}\n')
print('Sanity checks passed')
